import { supabase } from "./supabase";
import * as storage from "./jsonStorage";

// Helpers to map between local JSON and Supabase snake_case

function toSnakeCase(obj: any): any {
  if (Array.isArray(obj)) return obj.map(toSnakeCase);
  if (obj !== null && typeof obj === "object") {
    const newObj: any = {};
    for (const key in obj) {
      if (Object.prototype.hasOwnProperty.call(obj, key)) {
        const snakeKey = key.replace(
          /[A-Z]/g,
          (letter) => `_${letter.toLowerCase()}`,
        );
        newObj[snakeKey] = toSnakeCase(obj[key]);
      }
    }
    return newObj;
  }
  return obj;
}

function toCamelCase(obj: any): any {
  if (Array.isArray(obj)) return obj.map(toCamelCase);
  if (obj !== null && typeof obj === "object") {
    const newObj: any = {};
    for (const key in obj) {
      if (Object.prototype.hasOwnProperty.call(obj, key)) {
        const camelKey = key.replace(/_([a-z])/g, (g) => g[1].toUpperCase());
        newObj[camelKey] = toCamelCase(obj[key]);
      }
    }
    return newObj;
  }
  return obj;
}

export async function checkOnlineNewer(
  userId: number,
  localUpdatedAt: string,
): Promise<boolean> {
  const user = await storage.getUserById(userId);
  if (!user || !user.openId) return false;
  const { data, error } = await supabase
    .from("users")
    .select("updated_at")
    .eq("open_id", user.openId)
    .single();
  if (error || !data) return false;
  return new Date(data.updated_at) > new Date(localUpdatedAt);
}

export async function pushToSupabase(userId: number): Promise<void> {
  const user = await storage.getUserById(userId);
  if (!user || !user.openId) throw new Error("Usuário não tem OpenID");

  const db = JSON.parse(await storage.exportDatabase());

  // We sync disciplines, topics, revisions, mock_exams, notes, flashcards, question_errors, tec_snapshots

  // Get remote user_id internal
  const { data: remoteUser, error: uErr } = await supabase
    .from("users")
    .select("id")
    .eq("open_id", user.openId)
    .single();
  if (uErr || !remoteUser)
    throw new Error("Usuário não encontrado no Supabase");
  const remoteUserId = remoteUser.id;

  // Clear remote data
  const tables = [
    "revisions",
    "topics",
    "disciplines",
    "mock_exams",
    "notes",
    "flashcards",
    "question_errors",
    "tec_snapshots",
  ];
  for (const table of tables) {
    await supabase.from(table).delete().eq("user_id", remoteUserId);
  }

  // Insert records
  for (const table of tables) {
    const camelTable = table.replace(/_([a-z])/g, (g) => g[1].toUpperCase());
    const records =
      db[camelTable]?.filter((r: any) => r.userId === userId) || [];
    if (records.length === 0) continue;

    // Process in chunks of 100
    for (let i = 0; i < records.length; i += 100) {
      const chunk = records.slice(i, i + 100).map((r: any) => {
        const mapped = toSnakeCase(r);
        mapped.user_id = remoteUserId;
        delete mapped.id; // Let identity handle it or we map it?
        // Actually, if we delete id, foreign keys will break!
        // We MUST preserve IDs if possible, or we have to map them.
        return mapped;
      });
      // We need to keep IDs to preserve relations, so we must INSERT them. But identity columns might prevent it.
      // Assuming Supabase tables allow inserting IDs if they are GENERATED BY DEFAULT (but schema said GENERATED ALWAYS).
      // If they are GENERATED ALWAYS, we can't insert IDs! This is a huge problem.
    }
  }
}
